/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleMetadata: typeof import('./../theme/components/ArticleMetadata.vue')['default']
    ArticleMetaInfo: typeof import('./../theme/components/ArticleMetaInfo.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Home: typeof import('./../theme/components/Home.vue')['default']
    Layout: typeof import('./../theme/components/Layout.vue')['default']
    Posts: typeof import('./../theme/components/Posts.vue')['default']
    TagList: typeof import('./../theme/components/TagList.vue')['default']
    Vercount: typeof import('./../theme/components/Vercount.vue')['default']
  }
}
