/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
  }
}
